name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: arm-unknown-linux-gnueabihf
        override: true
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
#     - name: Build Pi
#       run: cargo build --release --target=arm-unknown-linux-gnueabihf
    - name: Run tests
      run: cargo test --verbose
